// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ThymeMe.Infrastructure.Persistence;

#nullable disable

namespace ThymeMe.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ThymeMeDbContext))]
    [Migration("20260824045813_PomodoroPauseOrigin")]
    partial class PomodoroPauseOrigin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("ThymeMe.Infrastructure.Persistence.AdjustmentCategoryRow", b =>
                {
                    b.Property<Guid>("AdjustmentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("AdjustmentId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("AdjustmentCategories", (string)null);
                });

            modelBuilder.Entity("ThymeMe.Infrastructure.Persistence.AdjustmentRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeletedUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DeletionBatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(16384)
                        .HasColumnType("TEXT");

                    b.Property<long>("EffectiveDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EstimatedEarningMinorUnits")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("HourlyRateMinorUnits")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LocalDateUnixDays")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("PurgeAfterUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RawDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RoundingIncrementMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundingRule")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("StreamId")
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted", "LocalDateUnixDays");

                    b.ToTable("Adjustments", (string)null);
                });

            modelBuilder.Entity("ThymeMe.Infrastructure.Persistence.CategoryRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ArchivedUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<bool>("DefaultBillable")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DeletionBatchId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("HourlyRateMinorUnits")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("PurgeAfterUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("StreamId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StreamId", "IsDeleted", "IsArchived");

                    b.ToTable("Categories", (string)null);
                });

            modelBuilder.Entity("ThymeMe.Infrastructure.Persistence.DeletionBatchRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("DeletedUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("PurgeAfterUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RootId")
                        .HasColumnType("TEXT");

                    b.Property<int>("RootKind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RootName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PurgeAfterUtcMilliseconds");

                    b.ToTable("DeletionBatches", (string)null);
                });

            modelBuilder.Entity("ThymeMe.Infrastructure.Persistence.ForegroundApplicationRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ExecutableFileName")
                        .IsRequired()
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "ExecutableFileName")
                        .IsUnique();

                    b.ToTable("ForegroundApplications", (string)null);
                });

            modelBuilder.Entity("ThymeMe.Infrastructure.Persistence.PaletteRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DarkAccent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DarkCanvas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DarkSurface")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FormatVersion")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBuiltIn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LightAccent")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LightCanvas")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LightSurface")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Palettes", (string)null);
                });

            modelBuilder.Entity("ThymeMe.Infrastructure.Persistence.ProjectRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ArchivedUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BudgetMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BudgetResetPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DeletionBatchId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("PurgeAfterUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("StreamId")
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("StreamId", "IsDeleted", "IsArchived");

                    b.ToTable("Projects", (string)null);
                });

            modelBuilder.Entity("ThymeMe.Infrastructure.Persistence.SchemaStateRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CleanShutdown")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ConsecutiveStartupFailures")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SchemaState", null, t =>
                        {
                            t.HasCheckConstraint("CK_SchemaState_Singleton", "Id = 1");
                        });
                });

            modelBuilder.Entity("ThymeMe.Infrastructure.Persistence.SessionCategoryRow", b =>
                {
                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("SessionId", "CategoryId");

                    b.HasIndex("CategoryId", "SessionId");

                    b.ToTable("SessionCategories", (string)null);
                });

            modelBuilder.Entity("ThymeMe.Infrastructure.Persistence.SessionRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("CompletionPending")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CreatedUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<long?>("DeletedUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DeletionBatchId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(16384)
                        .HasColumnType("TEXT");

                    b.Property<long>("EffectiveDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("EndUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EndUtcOffsetMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("EstimatedEarningMinorUnits")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("HourlyRateMinorUnits")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDraft")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Origin")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProjectOriginalName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("PurgeAfterUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RawDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("RequestedDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RoundingIncrementMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundingRule")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StartUtcOffsetMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("StreamId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StreamOriginalName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int>("TimingMode")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "StartUtcMilliseconds");

                    b.HasIndex("StreamId", "StartUtcMilliseconds");

                    b.HasIndex("IsDraft", "IsDeleted", "StartUtcMilliseconds");

                    b.ToTable("Sessions", (string)null);
                });

            modelBuilder.Entity("ThymeMe.Infrastructure.Persistence.SettingRow", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("JsonValue")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("TEXT");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Key");

                    b.ToTable("Settings", (string)null);
                });

            modelBuilder.Entity("ThymeMe.Infrastructure.Persistence.StreamRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("ArchivedUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("BudgetMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BudgetResetPeriod")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("DeletedUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("DeletionBatchId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("PurgeAfterUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IsDeleted", "IsArchived", "SortOrder");

                    b.ToTable("Streams", (string)null);
                });

            modelBuilder.Entity("ThymeMe.Infrastructure.Persistence.TimingRootRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("AccumulatedBreakMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long>("AccumulatedWorkMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CategoryIdsJson")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyCode")
                        .HasMaxLength(3)
                        .HasColumnType("TEXT");

                    b.Property<long>("CurrentSegmentStartedUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("HourlyRateMinorUnits")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBillable")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PausedFromStatus")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PomodoroBreakMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("PomodoroBreaksBillable")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PomodoroBufferMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PomodoroTotalMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("PomodoroWorkMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<long>("RequestedDurationMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Revision")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RoundingIncrementMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoundingRule")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ScheduledEndUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SingletonKey")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("StreamId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TimingMode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SingletonKey")
                        .IsUnique();

                    b.ToTable("TimingRoots", null, t =>
                        {
                            t.HasCheckConstraint("CK_TimingRoots_Singleton", "SingletonKey = 1");
                        });
                });

            modelBuilder.Entity("ThymeMe.Infrastructure.Persistence.TimingSegmentRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("EndUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("TEXT");

                    b.Property<long>("StartUtcMilliseconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "StartUtcMilliseconds");

                    b.ToTable("TimingSegments", (string)null);
                });

            modelBuilder.Entity("ThymeMe.Infrastructure.Persistence.AdjustmentCategoryRow", b =>
                {
                    b.HasOne("ThymeMe.Infrastructure.Persistence.AdjustmentRow", "Adjustment")
                        .WithMany("Categories")
                        .HasForeignKey("AdjustmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ThymeMe.Infrastructure.Persistence.CategoryRow", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Adjustment");
                });

            modelBuilder.Entity("ThymeMe.Infrastructure.Persistence.CategoryRow", b =>
                {
                    b.HasOne("ThymeMe.Infrastructure.Persistence.StreamRow", null)
                        .WithMany()
                        .HasForeignKey("StreamId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ThymeMe.Infrastructure.Persistence.ForegroundApplicationRow", b =>
                {
                    b.HasOne("ThymeMe.Infrastructure.Persistence.SessionRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ThymeMe.Infrastructure.Persistence.ProjectRow", b =>
                {
                    b.HasOne("ThymeMe.Infrastructure.Persistence.StreamRow", null)
                        .WithMany()
                        .HasForeignKey("StreamId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ThymeMe.Infrastructure.Persistence.SessionCategoryRow", b =>
                {
                    b.HasOne("ThymeMe.Infrastructure.Persistence.CategoryRow", null)
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ThymeMe.Infrastructure.Persistence.SessionRow", "Session")
                        .WithMany("Categories")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("ThymeMe.Infrastructure.Persistence.SessionRow", b =>
                {
                    b.HasOne("ThymeMe.Infrastructure.Persistence.ProjectRow", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ThymeMe.Infrastructure.Persistence.StreamRow", null)
                        .WithMany()
                        .HasForeignKey("StreamId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("ThymeMe.Infrastructure.Persistence.TimingSegmentRow", b =>
                {
                    b.HasOne("ThymeMe.Infrastructure.Persistence.SessionRow", null)
                        .WithMany()
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ThymeMe.Infrastructure.Persistence.AdjustmentRow", b =>
                {
                    b.Navigation("Categories");
                });

            modelBuilder.Entity("ThymeMe.Infrastructure.Persistence.SessionRow", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
